binance:
  live:
    api_key: ''
    secret_key: ''
  testnet:
    api_key: 
    secret_key: 
groq:
  api_key: 
  model: mixtral-8x7b-32768
llm:
  max_tokens: 1000
  temperature: 0.7
max_tokens: 1000
openai:
  api_key: ''
  model: gpt-4
trading:
  interval: 300
  max_amount: 1.0
  min_amount: 0.001
  symbol: BTC/USDT
